// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozakurpxxtqtxsxotqsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96YWt1cnB4eHRxdHhzeG90cXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODQ1MTAsImV4cCI6MjA2NTQ2MDUxMH0._bAv7iamP607qG6cLQYvQPsU2N9yB7XkVfhvicQRSkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);